version: '3.4'
volumes:
  relational-db-data:
services:
  db:
    platform: linux/x86_64
    image: percona:5.7.39
    restart: always
    volumes:
      - source: relational-db-data
        target: /var/lib/mysql
        type: volume
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: power-interview
  web:
    tty: true
    build: .
    command: bash -lc "bin/rails server -b 0.0.0.0"
    links:
      - db
    ports:
      - 3000:3000
    volumes:
      - source: .
        target: /home/app/src
        type: bind
