# Managed by https://github.com/powerhome/software. Do not make changes here, they will be reverted.

name: Automated Code Reviews
on: [pull_request]

jobs:
  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Brakeman
        uses: reviewdog/action-brakeman@5083efd49634e26645a0736681b618ccc3fb7f14 # v2
        with:
          brakeman_version: gemfile
  bearer:
    name: Bearer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1
        with:
          reviewdog_version: latest
      - name: Bearer
        uses: bearer/bearer-action@828eeb928ce2f4a7ca5ed57fb8b59508cb8c79bc # v2
        with:
          diff: true
          format: rdjson
          output: rd.json
      - name: Run reviewdog
        if: always()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          touch rd.json && cat rd.json | reviewdog -f=rdjson -reporter=github-pr-check
